### ISSUE TITLE
Getting error after saving file: "Exception: Unable to write to file 'NoneType' object is not subscriptable" 

### ISSUE THREAD

**Issue by krisz989898** [KenHuffman/UltimakerCuraScripts#3]
When I try to run the post processing script I get the error: "'NoneType' object is not subscriptable"

Currently on Cura 5.2.1 but I tried both version 5.1.1 and alpha release 5.3.0 and got the same error. This is the only post processing script that is running when I try to save the file. 

Here is the log for the related part: 
> 2023-01-06 22:21:55,043 - DEBUG - [MainThread] LocalFileOutputDevice.LocalFileOutputDevice.requestWrite [133]: Writing to [D:/3DBenchy_2h20m.gcode]...
2023-01-06 22:21:55,049 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail._createSnapshot [22]: Creating thumbnail image...
2023-01-06 22:21:55,053 - DEBUG - [MainThread] UM.Scene.Camera._preferencesChanged [255]: Changing perspective mode to perspective.
2023-01-06 22:21:55,055 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [61]: Loading [C:\Program Files\Ultimaker Cura 5.2.1\share\cura\resources\shaders\overhang.shader]...
2023-01-06 22:21:55,057 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [61]: Loading [C:\Program Files\Ultimaker Cura 5.2.1\share\cura\resources\shaders\transparent_object.shader]...
2023-01-06 22:21:55,058 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [61]: Loading [C:\Program Files\Ultimaker Cura 5.2.1\share\cura\resources\shaders\striped.shader]...
2023-01-06 22:21:55,316 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail._encodeSnapshot [30]: Encoding thumbnail image...
2023-01-06 22:21:55,328 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: Exception: Unable to write to file 3DBenchy_2h20m: 'NoneType' object is not subscriptable
2023-01-06 22:21:55,329 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: Traceback (most recent call last):
2023-01-06 22:21:55,330 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Qt\Bindings\OutputDeviceManagerProxy.py", line 150, in _writeToDevice
2023-01-06 22:21:55,330 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     device.requestWrite(nodes, file_name, limit_mimetypes, file_handler, **kwargs)
2023-01-06 22:21:55,331 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "C:\Program Files\Ultimaker Cura 5.2.1\share\uranium\plugins\LocalFileOutputDevice\LocalFileOutputDevice.py", line 148, in requestWrite
2023-01-06 22:21:55,331 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.writeStarted.emit(self)
2023-01-06 22:21:55,332 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 216, in emit
2023-01-06 22:21:55,332 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__handleEmitIndirect(*args, **kwargs)
2023-01-06 22:21:55,332 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 323, in __handleEmitIndirect
2023-01-06 22:21:55,333 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__performEmit(*args, **kwargs)
2023-01-06 22:21:55,333 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 361, in __performEmit
2023-01-06 22:21:55,334 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     signal.emit(*args, **kwargs)
2023-01-06 22:21:55,334 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 216, in emit
2023-01-06 22:21:55,334 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__handleEmitIndirect(*args, **kwargs)
2023-01-06 22:21:55,335 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 323, in __handleEmitIndirect
2023-01-06 22:21:55,335 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__performEmit(*args, **kwargs)
2023-01-06 22:21:55,335 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 357, in __performEmit
2023-01-06 22:21:55,336 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     func(dest, *args, **kwargs)
2023-01-06 22:21:55,336 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "C:\Program Files\Ultimaker Cura 5.2.1\share\cura\plugins\PostProcessingPlugin\PostProcessingPlugin.py", line 95, in execute
2023-01-06 22:21:55,337 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     gcode_list[0] += ";POSTPROCESSED\n"
2023-01-06 22:21:55,337 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: TypeError: 'NoneType' object is not subscriptable

**Comment by KenHuffman** [comment]
@krisz989898 Hmm. The traceback after the error does not have any line relating to my code, so this may be occurring after my plugin returns.

There was however a bug in my code that generated too many thumbnails in the gcode. In the process of that fix I added logging to the plugin so we can better determine if this problem is due to my code.

Please download the latest version of my plugin and try again. If you send my the STL that is failing for you I'll try it on my end.

**Comment by krisz989898** [comment]
Hi, I tried the new code with the logs and indeed the script ran fine. Here is the log: 
<details>
  <summary>logs</summary>

  ```
  2023-01-07 15:13:18,647 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail.execute [103]: CreateV2NeoThumbnail Plugin start with width=200, height=200...
2023-01-07 15:13:18,647 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail._createSnapshot [22]: Creating thumbnail image...
2023-01-07 15:13:18,648 - DEBUG - [MainThread] UM.Scene.Camera._preferencesChanged [255]: Changing perspective mode to perspective.
2023-01-07 15:13:18,650 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [61]: Loading [C:\Program Files\Ultimaker Cura 5.2.1\share\cura\resources\shaders\overhang.shader]...
2023-01-07 15:13:18,652 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [61]: Loading [C:\Program Files\Ultimaker Cura 5.2.1\share\cura\resources\shaders\transparent_object.shader]...
2023-01-07 15:13:18,653 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [61]: Loading [C:\Program Files\Ultimaker Cura 5.2.1\share\cura\resources\shaders\striped.shader]...
2023-01-07 15:13:18,885 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail.execute [107]: Snapshot created
2023-01-07 15:13:18,885 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail._encodeSnapshot [29]: Encoding thumbnail image...
2023-01-07 15:13:18,887 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail._encodeSnapshot [40]: Snapshot thumbnail_length=5358
2023-01-07 15:13:18,887 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail._convertSnapshotToGcode [46]: Converting snapshot into gcode...
2023-01-07 15:13:18,887 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail._convertSnapshotToGcode [54]: Gcode header=; jpg begin 200*200 5358 3 197 500
2023-01-07 15:13:18,888 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail.execute [112]: Layer count=304
2023-01-07 15:13:18,889 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail.execute [117]: Adding snapshot gcode lines (len=98) before ';FLAVOR:Marlin'
2023-01-07 15:13:18,889 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail.execute [122]: CreateV2NeoThumbnail Plugin end
2023-01-07 15:13:18,891 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: Exception: Unable to write to file 3DBenchy_2h02m: 'NoneType' object is not subscriptable
2023-01-07 15:13:18,893 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: Traceback (most recent call last):
2023-01-07 15:13:18,893 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Qt\Bindings\OutputDeviceManagerProxy.py", line 150, in _writeToDevice
2023-01-07 15:13:18,894 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     device.requestWrite(nodes, file_name, limit_mimetypes, file_handler, **kwargs)
2023-01-07 15:13:18,894 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "C:\Program Files\Ultimaker Cura 5.2.1\share\uranium\plugins\LocalFileOutputDevice\LocalFileOutputDevice.py", line 148, in requestWrite
2023-01-07 15:13:18,895 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.writeStarted.emit(self)
2023-01-07 15:13:18,895 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 216, in emit
2023-01-07 15:13:18,895 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__handleEmitIndirect(*args, **kwargs)
2023-01-07 15:13:18,896 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 323, in __handleEmitIndirect
2023-01-07 15:13:18,896 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__performEmit(*args, **kwargs)
2023-01-07 15:13:18,897 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 361, in __performEmit
2023-01-07 15:13:18,897 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     signal.emit(*args, **kwargs)
2023-01-07 15:13:18,897 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 216, in emit
2023-01-07 15:13:18,898 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__handleEmitIndirect(*args, **kwargs)
2023-01-07 15:13:18,898 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 323, in __handleEmitIndirect
2023-01-07 15:13:18,899 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     self.__performEmit(*args, **kwargs)
2023-01-07 15:13:18,899 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "UM\Signal.py", line 357, in __performEmit
2023-01-07 15:13:18,899 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     func(dest, *args, **kwargs)
2023-01-07 15:13:18,900 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:   File "C:\Program Files\Ultimaker Cura 5.2.1\share\cura\plugins\PostProcessingPlugin\PostProcessingPlugin.py", line 96, in execute
2023-01-07 15:13:18,900 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]:     gcode_list[0] += ";POSTPROCESSED\n"
2023-01-07 15:13:18,901 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: TypeError: 'NoneType' object is not subscriptable

  ```
</details>

So I started looking into cura's code and in the PostProcessingPlugin.py where the code broke and long story short, the end of the thumbnail creator script was an empty return, without the data. What is weird to me is that I copied it a few times and it was missing every time. Anyways it is fixed now, thank you for the quick response

**Comment by KenHuffman** [comment]
It appears from the latest log that this error appears in Cura **after** the plugin has already completed, this makes sense because the script doesn't actually write any files. I'm glad the plugin now works for you.

```
2023-01-07 15:13:18,889 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateV2NeoThumbnail.execute [122]: CreateV2NeoThumbnail Plugin end
2023-01-07 15:13:18,891 - ERROR - [MainThread] UM.Qt.Bindings.OutputDeviceManagerProxy._writeToDevice [163]: Exception: Unable to write to file 3DBenchy_2h02m: 'NoneType' object is not subscriptable

```
